### ISSUE TITLE
Update Pricing of StudentenwerkParser

### ISSUE THREAD

**Issue by lukasdenk** [TUM-Dev/eat-api#46]
The Studentenwerk changed its pricing
<img width="621" alt="Bildschirmfoto 2021-11-09 um 14 40 10" src="https://user-images.githubusercontent.com/63459921/140934457-2aaacf39-2d1f-497a-9e33-52d58c9f1a25.png">
:

Before, the category "Studitopf, Suppe" also contained "vegan".

I will change it soon :)

**Comment by Philipp000** [comment]
I just found out, that there is another issue regarding the pricing, which I'm not sure, if it is included in your issue.

For example, the "Tagessuppe" is displayed with a pricing of `1 + 0.33` for students. However, since it is Studitopf(StudieTopf?), it can't have a base price. An example can be seen for "mensa-garching" on 10.11.2021.

**Comment by COM8** [comment]
Yes. Saw this as well. Tagessuppe has a kind of broken price here :)
Perhaps we add a check if the name includes "suppe" and then set it to `0.33` without a base price?

**Comment by Philipp000** [comment]
I think, the issue can be found here:
https://github.com/TUM-Dev/eat-api/blob/69e04ad412d4f0d5687f38daf405780e27efc3b2/src/menu_parser.py#L167-L172

Once a dish is Studitopf, it shouldn't be considered for the non-vegetarian base price anymore.
However, since the Tagessuppe is `dish[0] == "Studitopf"` and `dish[4] == "0"` there is the non-vegetarian base price added.

**Comment by lukasdenk** [comment]
Yes, sorry, that was my mistake. I didn't realize that base prices only count for classic menus. I will fix it.
